services:
  app:
    build: .
    container_name: studentlife-java
    env_file:
      - .env
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/cloudflare:ro
    depends_on:
      - app